### ISSUE TITLE
疑似被别人上架play store了？

### ISSUE THREAD

**Issue by xuzhenglun** [GhostFlying/LocationReportEnabler#57]
包名被修改了，别的功能几乎一样的。

https://play.google.com/store/apps/details?id=org.cafeboy.locationreportenabler

**Comment by GhostFlying** [comment]
已知，暂不做处理，感谢通知。

**Comment by jumkey** [comment]
当时是想着方便自己和那些有洁癖的人使用才上架的，没有及时通知作者的确很不妥当。至于改包名只是为了不抢占原作者的包名。我这边先下架，同时期待正统版本能上线（我知道作者也有Google开发者账号😄）。

**Comment by GhostFlying** [comment]
其实我之前没上架打算就没打算管，既然这样我近期准备下发上去吧😀

**Comment by GhostFlying** [comment]
我已经向 Play 提交了，应该很快就能出现。

**Comment by jumkey** [comment]
什么情况啊 怎么又删了链接 @GhostFlying

**Comment by GhostFlying** [comment]
审核被 Google reject 了，涉嫌违反政策 4.3 4.4

We don’t allow apps that interfere with, disrupt, damage, or access in an
unauthorized manner the user’s device, other devices or computers, servers,
networks, application programming interfaces (APIs), or services, including
but not limited to other apps on the device, any Google service, or an
authorized carrier’s network.


On Thu, Feb 16, 2017, 9:29 PM Jumkey Chen <notifications@github.com> wrote:

什么情况啊 怎么又删了链接 @GhostFlying <https://github.com/GhostFlying>

—
You are receiving this because you were mentioned.


Reply to this email directly, view it on GitHub
<https://github.com/GhostFlying/LocationReportEnabler/issues/57#issuecomment-280330308>,
or mute the thread

**Comment by simonsmh** [comment]
那作者能发到coolapk上吗？
